export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    register: '/auth/register',
    me: '/auth/me',
    changePassword: '/auth/change-password',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  members: {
    list: '/members',
    detail: (id: string) => `/members/${id}`,
    create: '/members',
    update: (id: string) => `/members/${id}`,
    delete: (id: string) => `/members/${id}`,
    suspend: (id: string) => `/members/${id}/suspend`,
    unsuspend: (id: string) => `/members/${id}/unsuspend`,
    search: '/members/search',
    stats: '/members/stats',
  },
  subscriptions: {
    list: '/subscriptions',
    detail: (id: string) => `/subscriptions/${id}`,
    create: '/subscriptions',
    update: (id: string) => `/subscriptions/${id}`,
    delete: (id: string) => `/subscriptions/${id}`,
    renew: (id: string) => `/subscriptions/${id}/renew`,
    freeze: (id: string) => `/subscriptions/${id}/freeze`,
    unfreeze: (id: string) => `/subscriptions/${id}/unfreeze`,
    cancel: (id: string) => `/subscriptions/${id}/cancel`,
    byMember: (memberId: string) => `/members/${memberId}/subscriptions`,
  },
  plans: {
    list: '/plans',
    detail: (id: string) => `/plans/${id}`,
    create: '/plans',
    update: (id: string) => `/plans/${id}`,
    delete: (id: string) => `/plans/${id}`,
    active: '/plans/active',
  },
  classes: {
    list: '/classes',
    detail: (id: string) => `/classes/${id}`,
    create: '/classes',
    update: (id: string) => `/classes/${id}`,
    delete: (id: string) => `/classes/${id}`,
    schedule: '/classes/schedule',
    upcoming: '/classes/upcoming',
    cancel: (id: string) => `/classes/${id}/cancel`,
  },
  bookings: {
    list: '/bookings',
    detail: (id: string) => `/bookings/${id}`,
    create: '/bookings',
    cancel: (id: string) => `/bookings/${id}/cancel`,
    byMember: (memberId: string) => `/members/${memberId}/bookings`,
    byClass: (classId: string) => `/classes/${classId}/bookings`,
    checkIn: (id: string) => `/bookings/${id}/check-in`,
  },
  trainers: {
    list: '/trainers',
    detail: (id: string) => `/trainers/${id}`,
    create: '/trainers',
    update: (id: string) => `/trainers/${id}`,
    delete: (id: string) => `/trainers/${id}`,
    schedule: (id: string) => `/trainers/${id}/schedule`,
    stats: (id: string) => `/trainers/${id}/stats`,
  },
  payments: {
    list: '/payments',
    detail: (id: string) => `/payments/${id}`,
    create: '/payments',
    refund: (id: string) => `/payments/${id}/refund`,
    byMember: (memberId: string) => `/members/${memberId}/payments`,
    stats: '/payments/stats',
  },
  checkIns: {
    list: '/check-ins',
    create: '/check-ins',
    byMember: (memberId: string) => `/members/${memberId}/check-ins`,
    stats: '/check-ins/stats',
    today: '/check-ins/today',
  },
  notifications: {
    list: '/notifications',
    detail: (id: string) => `/notifications/${id}`,
    markRead: (id: string) => `/notifications/${id}/mark-read`,
    markAllRead: '/notifications/mark-all-read',
    delete: (id: string) => `/notifications/${id}`,
    unread: '/notifications/unread',
  },
  reports: {
    revenue: '/reports/revenue',
    attendance: '/reports/attendance',
    members: '/reports/members',
    subscriptions: '/reports/subscriptions',
    classes: '/reports/classes',
  },
  dashboard: {
    stats: '/dashboard/stats',
    recentActivity: '/dashboard/recent-activity',
    upcomingClasses: '/dashboard/upcoming-classes',
  },
};
